
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";

import type { paths } from "./generated"; // generated by openapi-typescript
import { envResolver } from "../env/env.resolver";

export const fetchClient = createFetchClient<paths>({
  baseUrl: envResolver.VITE_API_BASE_URL,
});

export const rqClient = createClient(fetchClient);
